### ISSUE TITLE
Question about OCRA deep learning model

### ISSUE THREAD

**Issue by zhijs** [jzhoulab/orca#1]
hi~, My name is yangzhi, I am a bioinformatics and deep learning enthusiast，it's so excited that learned the ORCA, a multiscale sequence modeling framework that predicts from sequence the 3D genome structure from kilobase-scale up to whole-chromosome-scale, but I was confused that whether ORCA framework can predicts all type cells's 3D genome structure from sequence by using just the same model, or we sholud train different model to predicts different type cells 3D genome structure from sequence. I see the freamwork use H1-ESC and HFF cells to train, I was wonder Whether this trained model can be applied to other type cells

**Comment by jzthree** [comment]
Thanks for your interest. Orca trains different models for predicting different cell types, and only predicts for cell types for which the training data is available (i.e. the main use of Orca models is intended for new sequences rather than new cell types).

BTW I will close this issue because usage questions should be directed to the google group orca-user@googlegroups.com. The issues is intended for bug reports and issues / suggestions directly related to the code.
